package https.paysecure.merchant_soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2020-07-05T15:37:04.024+05:30
 * Generated source version: 3.2.1
 * 
 */
@WebService(targetNamespace = "https://paysecure/merchant.soap/", name = "IssuerWebServiceSoap")
@XmlSeeAlso({https.paysecure.merchant.ObjectFactory.class, ObjectFactory.class})
public interface IssuerWebServiceSoap {

    @WebMethod(operationName = "VersionInfo", action = "https://paysecure/merchant.soap/VersionInfo")
    @RequestWrapper(localName = "VersionInfo", targetNamespace = "https://paysecure/merchant.soap/", className = "https.paysecure.merchant.VersionInfo")
    @ResponseWrapper(localName = "VersionInfoResponse", targetNamespace = "https://paysecure/merchant.soap/", className = "https.paysecure.merchant.VersionInfoResponse")
    @WebResult(name = "VersionInfoResult", targetNamespace = "https://paysecure/merchant.soap/")
    public java.lang.String versionInfo();

    @WebMethod(operationName = "CallPaySecure", action = "https://paysecure/merchant.soap/CallPaySecure")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "CallPaySecureResponse", targetNamespace = "https://paysecure/merchant.soap/", partName = "parameters")
    public https.paysecure.merchant.CallPaySecureResponse callPaySecure(
        @WebParam(partName = "RequestorCredentials", name = "RequestorCredentials", targetNamespace = "https://paysecure/merchant.soap.header/", header = true)
        RequestorCredentials requestorCredentials,
        @WebParam(partName = "parameters", name = "CallPaySecure", targetNamespace = "https://paysecure/merchant.soap/")
        https.paysecure.merchant.CallPaySecure parameters
    );
}
